sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: iOgt61/NI/QEkT/YMKeYdubj294eYfVn3rCKAfERHLuFM+fmxKdUPtSZEmUBAsjpMqbSWc55o/r2SCMsARk72N8lETCB+s37tNVkpzyFlLusvBbXOfH7M1OnsTiFThaVcDD/znz1PWEPVGuYKdjnogf6oz4ySe1ivbmQIgALsiqx5QBaEd9dGaaXpsj4VoDQzXvGpfor9dvM7a6J3+P9X7kJdj7MK5xRDnR+kpNqVnsiIw9ndGpUPj5SKqohFdKZyr/5aW95akkm2qwKn3rYBVs+2VdewAgMyCgRXjfjSZ7cHa4oTu5p+Y+O/CaK20R2/q4PFF4GwCU1iV80P6S8SYMnqqUQYuHB6XCLjosmpKCl+6EZ296GnXDH5unIZNjT99dPJPQJs/uTzyEDyh3kCtI59tP+M8D+Jr/UD1hdThORV018TkWzRjEfDk3xtwZG3EK5paXh8x6D0wJ85dYvPChS7l9hvKoWjOIQTZLzZof9gC3NFEl0nfYF1pOYTOhRzwrQtoLbAdyO/VS6kNpSdYL44Id/vGSJm4wpyTJAqaG/0m92+Iu4Ubf8XpE0OLqeE8leQnhb/2vULoKBvnOMKCo87tDlPH9DLLDSu4gWavn0Foc4h32m4bTvurdDOtQKfJf4oLLvRBr0UZOAGafm/pRhRNYpZ7xWeMKSbVdgcIA=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Kim_2226
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy